enabling actions
intel/compute-runtime pull request #260
Opened 2020-02-20 09:11 UTC by ArturHarasimiuk

Signed-off-by: Artur Harasimiuk <artur.harasimiuk@intel.com>

2020-02-20 11:25 UTC, AlexeySachkov commented on .github/workflows/ci.yml
> +      WORKFLOW: CI
```suggestion
      WORKFLOW: ${{ github.workflow}}
```

? Just to unify this line across different workflows

2020-02-20 11:27 UTC, AlexeySachkov commented on .github/workflows/verify.yml
> +      run: ./neo/scripts/actions/run-action-build.sh
I guess this should launch a different script, right?

Would it be better to just express it via separate job in the CI workflow?

2020-02-20 11:52 UTC, AlexeySachkov commented on .github/workflows/verify.yml
> +      run: ./run-action-docker-prepare.sh
What about using `steps.with`, or `steps.with.args`? ([docs](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepswith)) - it will clearly indicate which env variables are actually used and should be treated as arguments for the particular step

2021-02-19 02:03 UTC, Panquesito7 requested changes
I think you should also disable Travis CI, as GitHub Actions works much faster than Travis CI.

2021-02-19 02:03 UTC, Panquesito7 commented on .github/workflows/ci.yml
> +      - master
```suggestion
on: [push]
```

2021-02-19 02:03 UTC, Panquesito7 commented on .github/workflows/ci.yml
> +    - uses: actions/checkout@v2
```suggestion
    - uses: actions/checkout@master
```

2021-02-19 02:03 UTC, Panquesito7 commented on scripts/actions/run-action-build.sh
> +# Copyright (C) 2020 Intel Corporation
```suggestion
# Copyright (C) 2021 Intel Corporation
```

2021-02-19 02:03 UTC, Panquesito7 commented on scripts/actions/run-action-docker-prepare.sh
> +# Copyright (C) 2020 Intel Corporation
```suggestion
# Copyright (C) 2021 Intel Corporation
```

2021-02-19 02:03 UTC, Panquesito7 commented on .github/workflows/verify.yml
> +    - uses: actions/checkout@v2
```suggestion
    - uses: actions/checkout@master
```

2022-06-30 08:50 UTC, JablonskiMateusz commented
closing as deprecated

2022-06-30 08:50 UTC, closed without merging